### ISSUE TITLE
Resolve naming convention

### ISSUE THREAD

**Issue by mtmccrea** [mtmccrea/Hilbert#7]
Needs to be something that denotes:

- Hilbert transform
- method (Weaver, Hartley, PDN)
- returned signal (if only real or imaginary components)
- (optionally) filter type (FIR/IIR) to tell something about delay

For example:
**HilbertWRe** - Weaver Hilbert method, returning real part.
-or-
**HilbertWRe_IIR** - Weaver Hilbert method, returning real part, using the IIR (elliptic filter LPF), as opposed to PV_Brickwall (fft) version.

Other options:
**HilbertWea_Re**
**HilbertWeavRe_IIR**
**HilbertW_Re** (elliptic, IIR)
**HilbertW2_Re** (PV_Brickwall, FIR)
etc...

**Comment by joslloand** [comment]
Resolved in: https://github.com/ambisonictoolkit/Hilbert
